[0m00:37:45.132795 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017BD7383490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017BD732D190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017BD732E4D0>]}


============================== 00:37:45.156250 | bc211e16-61e9-4fae-af22-5541a0601e76 ==============================
[0m00:37:45.156250 [info ] [MainThread]: Running with dbt=1.9.4
[0m00:37:45.158148 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\saani\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt init', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m00:37:45.644367 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'WindowsPath'.. Dictionary: {'dir': WindowsPath('C:/Users/saani/.dbt')}
[0m00:37:45.646890 [info ] [MainThread]: Creating dbt configuration folder at 
[0m00:38:41.815802 [debug] [MainThread]: Starter project path: D:\NEU\Full time\projects\dbt_snowfalke\venv\Lib\site-packages\dbt\include\starter_project
[0m00:38:41.964433 [info ] [MainThread]: 
Your new dbt project "dbt_snowflake_pipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m00:38:41.967050 [info ] [MainThread]: Setting up your profile.
[0m00:44:21.037154 [info ] [MainThread]: Profile dbt_snowflake_pipeline written to C:\Users\saani\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m00:44:21.043143 [debug] [MainThread]: Command `dbt init` succeeded at 00:44:21.043143 after 396.10 seconds
[0m00:44:21.051310 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017BD737FA90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017BD5754710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017BD15BB390>]}
[0m00:44:21.054316 [debug] [MainThread]: Flushing usage events
[0m00:44:21.788925 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m01:26:13.691584 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3D6D28040>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3D7B7FD60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3D7B7FB80>]}


============================== 01:26:13.700632 | 836880f1-fc51-4cc1-872a-e64d511234a4 ==============================
[0m01:26:13.700632 [info ] [MainThread]: Running with dbt=1.9.4
[0m01:26:13.701743 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\saani\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m01:26:13.703253 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\NEU\Full time\projects\dbt_snowflake\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:26:13.705266 [debug] [MainThread]: Command `dbt run` failed at 01:26:13.705266 after 0.13 seconds
[0m01:26:13.706276 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3D6D28040>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3D7B7FE50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3D7B7FE20>]}
[0m01:26:13.706276 [debug] [MainThread]: Flushing usage events
[0m01:26:13.825140 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m20:21:27.820244 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023EA0797F70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023EA28D03D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023EA28D05B0>]}


============================== 20:21:27.826842 | 0484ba0b-15b6-43d7-bb59-1785f3ba6dc7 ==============================
[0m20:21:27.826842 [info ] [MainThread]: Running with dbt=1.9.4
[0m20:21:27.827848 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\saani\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m20:21:27.827848 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\NEU\Full time\projects\dbt_snowflake\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:21:27.828846 [debug] [MainThread]: Command `dbt run` failed at 20:21:27.828846 after 0.12 seconds
[0m20:21:27.829847 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023EA0797F70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023EA28D02E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023EA28D0310>]}
[0m20:21:27.829847 [debug] [MainThread]: Flushing usage events
[0m20:21:27.975199 [debug] [MainThread]: An error was encountered while trying to flush usage events
